version: "3.9"

services:
  dbh-redis-broker:
    build: .
    container_name: dbh-redis-broker
    image: dbh-redis-broker:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
